version: '3'
services:
    reverse:
        container_name: haciendola_reverse
        hostname: reverse
        image: nginx
        ports:
        - 80:80
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - postgres
    postgres:
        container_name: haciendola_postgres
        image: postgres
        volumes:
        - /private/var/lib/postgresql:/var/lib/postgresql
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: pguser
            POSTGRES_DB: pgdb

    nest:
        container_name: haciendola_nest
        build: .
        restart: unless-stopped
        depends_on: 
            - postgres
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app